# Generated by Django 5.2.3 on 2025-06-30 20:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('imagem', models.ImageField(upload_to='blog/')),
                ('conteudo', ckeditor.fields.RichTextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
