# Generated by Django 5.2.3 on 2025-07-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mensagemcontato_projetoportfolio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
    ]
