# Generated by Django 5.2.3 on 2025-07-09 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_blogpost_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensagemcontato',
            old_name='enviado_em',
            new_name='enviada_em',
        ),
        migrations.AlterField(
            model_name='mensagemcontato',
            name='assunto',
            field=models.CharField(max_length=150),
        ),
    ]
